### ISSUE TITLE
Question about Refresh modeling

### ISSUE THREAD

**Issue by liyiningxxxx** [tukl-msd/DRAMPetri#6]
In the paper "Fast Validation of DRAM Protocols with Timed Petri Nets", only tREFMAX=9 x tREFI was modeled, I believe it will cause some false negative situation. e.g. If the DDR Controller send a REFA command every (tREFMAX - 1)ns, that's definitely violating the protocal, but the model will not report any error.

**Comment by myzinsky** [comment]
Yes this could be the case, however in the successor of DRAMPetri DRAMml this is accounted.
